# Generated by Django 3.2.16 on 2022-11-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['date'], 'verbose_name': 'Акт', 'verbose_name_plural': 'Акты'},
        ),
        migrations.AlterModelOptions(
            name='actstatus',
            options={'ordering': ['key'], 'verbose_name': 'Статус акта', 'verbose_name_plural': 'Статусы актов'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['date'], 'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='contractstatus',
            options={'ordering': ['key'], 'verbose_name': 'Статус договора', 'verbose_name_plural': 'Статусы договоров'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'ordering': ['key'], 'verbose_name': 'Статус платежа', 'verbose_name_plural': 'Статусы платежей'},
        ),
        migrations.AlterModelOptions(
            name='prepaidclosemethod',
            options={'ordering': ['key'], 'verbose_name': 'Способ закрытия аванса', 'verbose_name_plural': 'Способы закрытия аванса'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='actstatus',
            name='key',
            field=models.IntegerField(default=0, verbose_name='Код для алгоритма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractstatus',
            name='key',
            field=models.IntegerField(default=0, verbose_name='Код для алгоритма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='key',
            field=models.IntegerField(default=0, verbose_name='Код для алгоритма'),
            preserve_default=False,
        ),
    ]
