# Generated by Django 3.2.16 on 2022-12-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('incoming', '0003_auto_20221205_0935'), ('incoming', '0004_auto_20221219_1513')]

    dependencies = [
        ('incoming', '0002_auto_20221129_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incoming.contract', verbose_name='Договор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='act',
            name='material_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='act',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incoming.actstatus', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='act',
            name='total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='act',
            name='work_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Работы'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='material_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='prepaid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Аванс'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incoming.project', verbose_name='Проект'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='retention_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент удержания с КС'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incoming.contractstatus', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='work_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Работы'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incoming.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='prepaid_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма аванса'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incoming.paymentstatus', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='act',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='act',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.actstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.contractstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.paymentstatus', verbose_name='Статус'),
        ),
    ]
