# Generated by Django 3.2.16 on 2022-12-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0003_auto_20221205_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='act',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.actstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.contractstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.paymentstatus', verbose_name='Статус'),
        ),
    ]
