# Generated by Django 3.2.16 on 2023-01-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0003_auto_20221205_0935_squashed_0004_auto_20221219_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='retention_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма удержаний'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Общая сумма'),
        ),
    ]
