# Generated by Django 3.2.16 on 2023-01-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0004_auto_20230126_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения')),
                ('model', models.CharField(max_length=255, null=True, verbose_name='Таблица')),
                ('user', models.CharField(max_length=255, null=True, verbose_name='Автор изменения')),
                ('action_on_model', models.CharField(choices=[(2, 'Изменение в записи'), (1, 'Новая запись'), (3, 'Удаление записи')], max_length=50, null=True, verbose_name='Действие')),
                ('data', models.JSONField(verbose_name='Изменяемые данные модели')),
            ],
            options={
                'verbose_name': 'Запись об изменении',
                'verbose_name_plural': 'История изменений',
                'ordering': ['changed'],
            },
        ),
    ]
