# Generated by Django 3.2.16 on 2023-01-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0005_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='action_on_model',
            field=models.CharField(choices=[['create', 'Новая запись'], ['update', 'Изменение в записи'], ['delete', 'Удаление записи']], max_length=50, null=True, verbose_name='Действие'),
        ),
    ]
