# Generated by Django 3.2.16 on 2023-09-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0007_changelog_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(db_index=True, max_length=12, verbose_name='ИНН')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('buy', 'Закупка')], default='sale', max_length=10, verbose_name='Тип договора'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='action_on_model',
            field=models.CharField(choices=[('create', 'Новая запись'), ('update', 'Изменение в записи'), ('delete', 'Удаление записи')], max_length=50, null=True, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='prepaid_close_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.prepaidclosemethod', verbose_name='Удержание аванса'),
        ),
        migrations.AddField(
            model_name='contract',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.partner', verbose_name='Контрагент'),
        ),
    ]
